name: Upload Download Artifactory

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          mkdir -p output
          echo "This is a build output file" > output/build.txt

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: output/
          
      - name: Download build output
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: ./downloaded-output

      - name: Use build output
        run: cat ./downloaded-output/build.txt