name: CI Workflow

'on':
  workflow_dispatch: { }

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Run build
        run: |
          echo "Building project..."
          # Simulate a build failure for demonstration purposes
          exit 1

      - name: Send failure notification
        if: ${{ failure() }}
        run: echo "Build failed. Sending notification..."
