name: CI Workflow

'on':
  workflow_dispatch: { }

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Run build
        run: |
          echo "Building project..."
          # Simulate a build failure for demonstration purposes
          exit 1

      - name: Send failure notification
        if: ${{ failure() }}
        run: echo "Build failed. Sending notification..."
        
      - name: Run build
        if: ${{ failure() }}
        run: |
          echo "Building project..."
          # Simulate a build success for demonstration purposes
          exit 0
 
      - name: Send failure notification again
        if: ${{ failure() }}
        run: echo "Build failed. Sending notification..."
        
      - name: Send success notification
        if: ${{ success() }}
        run: echo "Build success. Sending notification..."
        
      - name: Always
        if: ${{ always() }}
        run: echo "Always..."
