name: hello-world
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: df -kh
      - name: command1
        run: pwd 
      - name: command2
        run: echo "parwez" > 1.txt
      - name: command3
        run: ls
      - name: command4
        run: cat 1.txt
      - name: command5
        run: |
         whoami
         lsb_release -a 
         ls /home/runner/work/parwezalam/
         echo "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
         ls /home/runner/work/parwezalam/parwezalam
         echo "AAAAAAAAAAAAAAAAAAAAAAAAAAAA"
         ls /opt
         echo "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP"
         ls /opt/hostedtoolcache
         echo "KKKKKKKKKKKKKKKKKKKKKK"
         ls /home
         echo "MMMMMMMMMMMMMMMMMMMMMMMMMM"
         ls /home/runner
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: command6
        run: |
         whoami
         lsb_release -a 
         ls /home/runner/work/parwezalam/
         echo "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
         ls /home/runner/work/parwezalam/parwezalam
         echo "AAAAAAAAAAAAAAAAAAAAAAAAAAAA"
         ls /opt
         echo "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP"
         ls /opt/hostedtoolcache
         echo "KKKKKKKKKKKKKKKKKKKKKK"
         ls /home
         echo "MMMMMMMMMMMMMMMMMMMMMMMMMM"
         ls /home/runner
  my-job2:
    runs-on: windows-latest
    steps:
      - name: my-step2
        run: echo "Hello World!"
      - name: command1
        run: pwd 
      - name: command2
        run: echo "parwez" > 1.txt
      - name: command3
        run: ls
      - name: command4
        run: cat 1.txt
