name: hello-world
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: command1
        run: pwd 
      - name: command2
        run: echo "parwez" > 1.txt
      - name: command3
        run: ls
      - name: command4
        run: cat 1.txt
      - name: command5
        run: |
         whoami
         echo KKK 
  my-job2:
    runs-on: windows-latest
    steps:
      - name: my-step2
        run: echo "Hello World!"
      - name: command1
        run: pwd 
      - name: command2
        run: echo "parwez" > 1.txt
      - name: command3
        run: ls
      - name: command4
        run: cat 1.txt
