# This workflow will build a Java project with Gradle a
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Self Java CI with Gradle

on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  sel-build-java:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2

    - name: pwd
      run: pwd
           
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: alamparwez/demo-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
         
